version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - url-shortener-network
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - url-shortener-network
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - MONGO_URI=mongodb://mongo:27017
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - redis
      - mongo
    networks:
      - url-shortener-network

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - REDIS_ADDR=redis:6379
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - redis
      - mongo
    networks:
      - url-shortener-network
    command: ["go", "test", "-v", "./..."]
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - url-shortener-network
    volumes:
      - "/home/ahmed/url-shortener/nginx.conf:/etc/nginx/nginx.conf:ro"
networks:
  url-shortener-network:
    driver: bridge

volumes:
  redis-data:
  mongo-data:
